-- Akira アキラ — palette (Hyprland 0.55+, Lua config)
-- theme/palette.lua
--
-- GENERATED by scripts/theme.sh — do not edit by hand.
-- Source: theme/akira.env

return {
  -- Surfaces
  bg          = "#1A1B26",
  bg_dark     = "#16161E",
  bg_alt      = "#1F2335",
  surface     = "#24283B",
  highlight   = "#292E42",

  -- Borders
  border      = "#414868",
  border_hi   = "#7AA2F7",

  -- Text
  fg          = "#C0CAF5",
  fg_dark     = "#A9B1D6",
  comment     = "#565F89",

  -- Accents
  accent      = "#F7768E",
  red         = "#F7768E",
  orange      = "#FF9E64",
  yellow      = "#E0AF68",
  green       = "#9ECE6A",
  teal        = "#73DACA",
  cyan        = "#7DCFFF",
  blue        = "#7AA2F7",
  magenta     = "#BB9AF7",

  -- Alpha variants, for borders, shadows and blur
  border_a    = "#414868ff",
  border_hi_a = "#7AA2F7ee",
  magenta_a   = "#BB9AF7ee",
  shadow_a    = "#16161E80",
}
