#!/bin/bash

# Akira - configuration symlinks
#
# Can be sourced by config.sh or run on its own after a git pull:
#   bash ~/.akira/scripts/link.sh

source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/env.sh"

# Where pre-existing files are kept before being replaced by a symlink
export AKIRA_BACKUP_PATH="$HOME/.akira-backup"

# Create a symlink idempotently, preserving whatever was already there
akira_link() {
  local src="$1"
  local dst="$2"

  # Already the exact link we want: nothing to do
  if [ -L "$dst" ] && [ "$(readlink "$dst")" = "$src" ]; then
    return
  fi

  mkdir -p "$(dirname "$dst")"

  # Something is in the way (real file, directory or stale link): back it up
  if [ -e "$dst" ] || [ -L "$dst" ]; then
    local rel="${dst#"$HOME"/}"
    mkdir -p "$AKIRA_BACKUP_PATH/$(dirname "$rel")"
    mv "$dst" "$AKIRA_BACKUP_PATH/$rel"
    echo "  backup: $dst"
  fi

  ln -sfn "$src" "$dst"
  echo "  link:   $dst"
}

# Mirror a file tree, creating one symlink per file
akira_link_tree() {
  local src_dir="$1"
  local dst_dir="$2"
  local file rel

  while IFS= read -r -d '' file; do
    rel="${file#"$src_dir"/}"
    akira_link "$file" "$dst_dir/$rel"
  done < <(find "$src_dir" -type f -print0)
}

# Remove broken links pointing back into the repository
# (files that were deleted from Akira)
akira_prune_links() {
  local dst_dir="$1"
  [ -d "$dst_dir" ] || return
  find "$dst_dir" -xtype l -lname "$AKIRA_DIR_PATH/*" -print -delete
}

# wofi resolves @import against its own working directory instead of the
# stylesheet location, so imports are unreliable there. The shared colors are
# concatenated into the final stylesheet instead. The rules stay in wofi.css,
# under version control and symlinked like everything else.
akira_generate_wofi_style() {
  local dst="$HOME_CONFIG_PATH/wofi/style.css"
  local colors="$AKIRA_CONFIG_PATH/home_config/akira_style/style.css"
  local rules="$AKIRA_CONFIG_PATH/home_config/wofi/wofi.css"
  local src

  # Fail loudly instead of leaving wofi with an empty stylesheet
  for src in "$colors" "$rules"; do
    if [ ! -s "$src" ]; then
      echo "  ERROR:  missing or empty $src" >&2
      return 1
    fi
  done

  mkdir -p "$(dirname "$dst")"
  # Drop any symlink first, otherwise the redirect writes into the repository
  rm -f "$dst"

  {
    echo "/* Generated by link.sh - edit wofi.css instead */"
    echo
    cat "$colors"
    echo
    cat "$rules"
  } >"$dst"

  echo "  gen:    $dst ($(wc -c <"$dst") bytes)"
}

echo -e "# Linking configuration files"
akira_link_tree "$AKIRA_CONFIG_PATH/home_config" "$HOME_CONFIG_PATH"
akira_link_tree "$AKIRA_CONFIG_PATH/.gnupg" "$HOME/.gnupg"
akira_link "$AKIRA_CONFIG_PATH/.XCompose" "$HOME/.XCompose"

# gpg requires a restrictive mode on the directory, which stays a real dir
chmod 700 "$HOME/.gnupg"

echo -e "# Generating user specific files"
akira_generate_wofi_style

echo -e "# Pruning dangling links"
akira_prune_links "$HOME_CONFIG_PATH"
akira_prune_links "$HOME/.gnupg"
