#!/bin/bash

echo -e "# Pacman package manager full system update and packages install"
sudo cp $AKIRA_CONFIG_PATH/pacman.conf /etc/pacman.conf
sudo pacman -Syu --noconfirm
sudo pacman -S --noconfirm \
  libimobiledevice \
  usbmuxd \
  ifuse \
  gvfs-afc \
  linux-headers \
  dkms \
  fwupd \
  iwd \
  networkmanager \
  nmap \
  wavemon \
  mtr \
  cups \
  avahi \
  gst-plugins-ugly \
  gst-plugins-good \
  gst-plugins-base \
  gst-plugins-bad \
  gst-libav \
  gstreamer \
  ntfs-3g \
  exfat-utils \
  flatpak \
  hyprpolkitagent \
  hyprpaper \
  hyprlock \
  waybar \
  wofi \
  kanshi \
  wl-clipboard \
  kitty \
  fish \
  starship \
  git \
  curl \
  less \
  jq \
  zip \
  ffmpeg \
  mpv \
  mpv-mpris \
  yt-dlp \
  neovim \
  fastfetch \
  spotify-player \
  pass \
  pass-otp \
  mise \
  texlive \
  texlive-langportuguese \
  biber \
  wiremix \
  playerctl \
  brightnessctl \
  bluetui \
  btop \
  amdgpu_top \
  task \
  taskwarrior-tui \
  docker \
  docker-compose \
  wine \
  gamemode \
  gamescope \
  hplip \
  piper \
  simple-scan \
  chromium \
  nautilus \
  sushi \
  gnome-calculator \
  papers \
  gnome-font-viewer \
  gnome-firmware \
  fragments \
  handbrake \
  secrets \
  loupe \
  nwg-look \
  zathura \
  zathura-pdf-poppler \
  noto-fonts \
  noto-fonts-emoji \
  noto-fonts-cjk \
  ttf-jetbrains-mono-nerd \
  ttf-liberation \
  papirus-icon-theme
